classification: Journals
publishedDate: 2021. 02. 05.
title: Developing a Product Knowledge Graph of Consumer Electronics to Manage Sustainable Product Information
author: Haklae Kim
description: Sustainability 2021, 13, 1722.
link: https://doi.org/10.3390/su13041722
